# Generated by Django 5.0.7 on 2024-12-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_district_user_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='street_name',
            new_name='street',
        ),
    ]
