# Generated by Django 5.1.4 on 2024-12-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rename_street_name_user_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
    ]
