# Generated by Django 5.0.7 on 2024-12-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonVegMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('picture', models.ImageField(null=True, upload_to='picture/')),
            ],
        ),
        migrations.CreateModel(
            name='VegMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('picture', models.ImageField(null=True, upload_to='picture/')),
            ],
        ),
    ]
