# Generated by Django 5.1.3 on 2024-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_nonvegmenu_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegmenu',
            name='food_type',
            field=models.CharField(choices=[('briyani', 'Briyani'), ('meals', 'Meals'), ('starters', 'Starters'), ('varierty rice', 'Variety Rice'), ('dosa', 'Dosa'), ('rotti', 'Rotti'), ('gravies', 'Gravies'), ('cold beverages', 'Cold Beverages'), ('hot beverages', 'Hot Beverages'), ('snacks', 'Snacks'), ('ice cream', 'Ice Cream')], default='briyani', max_length=50),
        ),
        migrations.AlterField(
            model_name='nonvegmenu',
            name='food_type',
            field=models.CharField(choices=[('briyani', 'Briyani'), ('meals', 'Meals'), ('starters', 'Starters'), ('fried rice', 'Fried Rice'), ('dosa', 'Dosa'), ('rotti', 'Rotti'), ('gravies', 'Gravies'), ('cold beverages', 'Cold Beverages'), ('hot beverages', 'Hot Beverages'), ('snacks', 'Snacks'), ('ice cream', 'Ice Cream')], default='briyani', max_length=50),
        ),
    ]
