# Generated by Django 5.0.7 on 2024-12-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_order_created_at_order_gst_order_handling_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='order',
            name='handling_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
