# Generated by Django 5.0.7 on 2024-12-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_order_gst_remove_order_handling_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonvegmenu',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vegmenu',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
