# Generated by Django 5.0.7 on 2024-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_nonvegmenu_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonvegmenu',
            name='food_type',
            field=models.CharField(choices=[('briyani', 'Briyani'), ('meals', 'Meals'), ('starters', 'Starters'), ('fried rice', 'Fried Rice'), ('dosa', 'Dosa'), ('rotti', 'Rotti'), ('gravies', 'Gravies'), ('snacks', 'Snacks')], default='briyani', max_length=50),
        ),
    ]
