# Generated by Django 5.0.7 on 2024-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_nonvegmenu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonvegmenu',
            name='food_type',
            field=models.CharField(choices=[('nv briyani', 'NV Briyani'), ('nv meals', 'NV Meals'), ('nv starters', 'NV Starters'), ('nv fried rice', 'NV Fried Rice'), ('nv dosa', 'NV Dosa'), ('nv rotti', 'NV Rotti'), ('nv gravies', 'NV Gravies'), ('nv snacks', 'NV Snacks')], default='briyani', max_length=50),
        ),
    ]
