# Generated by Django 5.0.7 on 2024-12-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_nonvegmenu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonvegmenu',
            name='food_type',
            field=models.CharField(choices=[('nv briyani', 'Non Veg Briyani'), ('nv meals', 'Non Veg Meals'), ('nv starters', 'Non Veg Starters'), ('nv fried rice', 'Non Veg Fried Rice'), ('nv dosa', 'Non Veg Dosa'), ('nv rotti', 'Non Veg Rotti'), ('nv gravies', 'Non Veg Gravies'), ('nv snacks', 'Non Veg Snacks')], default='briyani', max_length=50),
        ),
    ]
