# Generated by Django 5.0.7 on 2024-12-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
