# Generated by Django 5.0.7 on 2024-12-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_remove_cartitem_cart_delete_cart_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
