# Generated by Django 5.0.7 on 2024-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nonveg_products',
            field=models.ManyToManyField(blank=True, related_name='order_nonveg_products', to='menu.nonvegmenu'),
        ),
        migrations.AddField(
            model_name='order',
            name='veg_products',
            field=models.ManyToManyField(blank=True, related_name='order_veg_products', to='menu.vegmenu'),
        ),
    ]
