# Generated by Django 5.0.7 on 2024-12-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_order_nonveg_products_order_veg_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nonveg_products',
            field=models.ManyToManyField(blank=True, related_name='orders', to='menu.nonvegmenu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='veg_products',
            field=models.ManyToManyField(blank=True, related_name='orders', to='menu.vegmenu'),
        ),
        migrations.AlterField(
            model_name='vegmenu',
            name='food_type',
            field=models.CharField(choices=[('briyani', 'Briyani'), ('meals', 'Meals'), ('starters', 'Starters'), ('variety rice', 'Variety Rice'), ('dosa', 'Dosa'), ('rotti', 'Rotti'), ('gravies', 'Gravies'), ('cold beverages', 'Cold Beverages'), ('hot beverages', 'Hot Beverages'), ('snacks', 'Snacks'), ('ice cream', 'Ice Cream')], default='briyani', max_length=50),
        ),
    ]
