# Generated by Django 5.0.7 on 2024-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_alter_order_nonveg_products_alter_order_veg_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nonveg_products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='veg_products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='menu.vegmenu'),
        ),
    ]
