# Generated by Django 5.1.3 on 2024-12-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_remove_order_products_order_nonveg_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nonveg_products',
        ),
    ]
