# Generated by Django 5.1.4 on 2024-12-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
